force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <pluralLabel>Reservations</pluralLabel>
    <nameField>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
        <displayFormat>RES-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipName>CustomerReservations</relationshipName>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <label>Number of Guests</label>
    <type>Number</type>
    <precision>3</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Reservation_DateTime__c.field-meta.xml
<CustomField>
  <fullName>Reservation_DateTime__c</fullName>
  <label>Reservation DateTime</label>
  <type>DateTime</type>
  <required>true</required>
  <description>Stores combined date and time for reservation</description>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Table__c.field-meta.xml
<CustomField>
    <fullName>Table__c</fullName>
    <label>Table</label>
    <type>Lookup</type>
    <referenceTo>Table__c</referenceTo>
    <relationshipName>TableReservations</relationshipName>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
  <label>Table</label>
  <pluralLabel>Tables</pluralLabel>
  <nameField>
    <label>Table Number</label>
    <type>Text</type>

  </nameField>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReservationController.cls
public with sharing class ReservationController {
    @AuraEnabled
    public static Id createReservation(Id customerId, Integer noOfGuests,Datetime reservationDateTime, Id tableId) {

        Reservation__c Res = new Reservation__C(
             Customer__c = customerId,
             Number_of_Guests__c = noOfGuests,
             Reservation_DateTime__c = reservationDateTime,
             Table__c = tableId
        );

        insert Res;
        return Res.Id;
    }
}