force-app/main/default/objects/Menu_Item__c/Menu_Item__c.object-meta.xml
<CustomObject>
  <label>Menu Item</label>
  <pluralLabel>Menu Items</pluralLabel>
  <nameField>
    <label>Menu Item Name</label>
    <type>Text</type>
  </nameField>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <pluralLabel>Orders</pluralLabel>
    <nameField>
        <label>Order Number</label>
        <type>AutoNumber</type>
        <displayFormat>ORD-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <label>Reservation</label>
    <type>Lookup</type>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipName>Reservation</relationshipName>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
  <label>Order Line Item</label>
  <pluralLabel>Order Line Items</pluralLabel>
  <nameField>
    <label>Line Item Number</label>
    <type>AutoNumber</type>
    <displayFormat>OLI-{0000}</displayFormat>
  </nameField>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Menu_Item__c.field-meta.xml
<CustomField>
  <fullName>Menu_Item__c</fullName>
  <label>Menu Item</label>
  <type>Lookup</type>
  <referenceTo>Menu_Item__c</referenceTo>
  <relationshipName>MenuItem</relationshipName>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
  <fullName>Order__c</fullName>
  <label>Order</label>
  <type>Lookup</type>
  <referenceTo>Order__c</referenceTo>
  <relationshipName>OrderLineItems</relationshipName>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
  <fullName>Price__c</fullName>
  <label>Price</label>
  <type>Currency</type>
  <precision>10</precision>
  <scale>2</scale>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
  <fullName>Quantity__c</fullName>
  <label>Quantity</label>
  <type>Number</type>
  <precision>5</precision>
  <scale>0</scale>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <pluralLabel>Reservations</pluralLabel>
    <nameField>
        <label>Reservation Number</label>
        <type>AutoNumber</type>
        <displayFormat>RES-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {
    public class OrderItemWrapper{
        @AuraEnabled public Id menuItemId{get; set;}
        @AuraEnabled public Integer quantity{get; set;}
        @AuraEnabled public Decimal price{get; set;}

    }

    @AuraEnabled
    public static Id createOrder(Id reservationId, List<OrderItemWrapper> items) {
         Order__c order = new Order__c(
            Reservation__c = reservationId,
            Order_Status__c = 'New'
         );

         insert order;

         List<Order_Line_Item__C> orderItems = new List<Order_Line_Item__c>();

         for(OrderItemWrapper i:items){
            orderItems.add(new Order_Line_Item__c(
                Order__c = order.Id,
                Menu_Item__c = i.menuItemId,
                Quantity__c = i.quantity,
                Price__c = i.price
            ));
         }

         insert orderItems;
         return order.Id;
    }
}